# Generated by Django 3.1.2 on 2020-10-27 16:53

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_user_even_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='even_number',
            field=models.IntegerField(help_text='Make sure its an even number', name='e3'),
        ),
    ]
