# Generated by Django 3.1.2 on 2020-10-27 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201027_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='even_number',
        ),
    ]
