# Generated by Django 3.1.2 on 2020-10-27 17:09

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_user_even_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='even',
            field=models.IntegerField(default=0, name='e1'),
        ),
    ]
